const LAPTOP_DATA = [
  {
    "Model_ID": "DELL-INS3530-1335U",
    "Category": "Productive",
    "Price": 47470,
    "CPU_Model": "i5-1335U",
    "CPU_Gen_Series": "13",
    "GPU_Type": "Intel Iris Xe",
    "TGP_W": 28,
    "Screen_Specs": "15.6\" FHD IPS 120Hz",
    "User_Category": "Productive",
    "Series": "13th Gen (Raptor Lake)",
    "Launch Year": 2023,
    "Naming Example": "Starts with 13xxx",
    "Key Changes & Scam Detector Rule": "Excellent efficiency and performance. Highly Recommended.",
    "Recommendation": "Highly Recommended",
    "Rating": 9,
    "Purchase link": "https://www.amazon.in/s?k=DELL-INS3530-1335U&i=computers"
  },
  {
    "Model_ID": "HP-15-1335U-DDR4",
    "Category": "Productive",
    "Price": 54990,
    "CPU_Model": "i5-1335U",
    "CPU_Gen_Series": "13",
    "GPU_Type": "Intel Iris Xe",
    "TGP_W": 28,
    "Screen_Specs": "15.6\" FHD Anti-Glare",
    "User_Category": "Productive",
    "Series": "13th Gen (Raptor Lake)",
    "Launch Year": 2023,
    "Naming Example": "Starts with 13xxx",
    "Key Changes & Scam Detector Rule": "Excellent efficiency and performance. Highly Recommended.",
    "Recommendation": "Highly Recommended",
    "Rating": 9,
    "Purchase link": "https://www.amazon.in/s?k=HP-15-1335U-DDR4&i=computers"
  },
  {
    "Model_ID": "SAMSUNG-GB4-1335U",
    "Category": "Productive",
    "Price": 51719,
    "CPU_Model": "i5-1335U",
    "CPU_Gen_Series": "13",
    "GPU_Type": "Intel Iris Xe",
    "TGP_W": 28,
    "Screen_Specs": "15.6\" FHD 60Hz",
    "User_Category": "Productive",
    "Series": "13th Gen (Raptor Lake)",
    "Launch Year": 2023,
    "Naming Example": "Starts with 13xxx",
    "Key Changes & Scam Detector Rule": "Excellent efficiency and performance. Highly Recommended.",
    "Recommendation": "Highly Recommended",
    "Rating": 9,
    "Purchase link": "https://www.amazon.in/s?k=SAMSUNG-GB4-1335U&i=computers"
  },
  {
    "Model_ID": "ASUS-VB14-1335U",
    "Category": "Productive",
    "Price": 45990,
    "CPU_Model": "i5-1335U",
    "CPU_Gen_Series": "13",
    "GPU_Type": "Intel Iris Xe",
    "TGP_W": 28,
    "Screen_Specs": "14\" FHD IPS",
    "User_Category": "Productive",
    "Series": "13th Gen (Raptor Lake)",
    "Launch Year": 2023,
    "Naming Example": "Starts with 13xxx",
    "Key Changes & Scam Detector Rule": "Excellent efficiency and performance. Highly Recommended.",
    "Recommendation": "Highly Recommended",
    "Rating": 9,
    "Purchase link": "https://www.amazon.in/s?k=ASUS-VB14-1335U&i=computers"
  },
  {
    "Model_ID": "LENOVO-IP1-5500U-RY",
    "Category": "Productive",
    "Price": 33080,
    "CPU_Model": "Ryzen 5 5500U",
    "CPU_Gen_Series": "5000",
    "GPU_Type": "Radeon Vega",
    "TGP_W": 15,
    "Screen_Specs": "15.6\" FHD IPS",
    "User_Category": "Productive",
    "Series": "Ryzen 5000 Series (Zen 3)",
    "Launch Year": 2021,
    "Naming Example": "Starts with 5xxx",
    "Key Changes & Scam Detector Rule": "Zen 3 architecture with solid efficiency. Acceptable but older.",
    "Recommendation": "Acceptable",
    "Rating": 7,
    "Purchase link": "https://www.amazon.in/s?k=LENOVO-IP1-5500U-RY&i=computers"
  },
  {
    "Model_ID": "HP-VICTUS-13620H-RTX3050",
    "Category": "Creative",
    "Price": 102990,
    "CPU_Model": "i7-13620H",
    "CPU_Gen_Series": "13",
    "GPU_Type": "RTX 3050 (6GB)",
    "TGP_W": 75,
    "Screen_Specs": "15.6\" FHD IPS 144Hz",
    "User_Category": "Creative",
    "Series": "13th Gen (Raptor Lake)",
    "Launch Year": 2023,
    "Naming Example": "Starts with 13xxx",
    "Key Changes & Scam Detector Rule": "Excellent efficiency and performance. Highly Recommended.",
    "Recommendation": "Highly Recommended",
    "Rating": 9,
    "Purchase link": "https://www.amazon.in/s?k=HP-VICTUS-13620H-RTX3050&i=computers"
  },
  {
    "Model_ID": "HP-VICTUS-i5-13420H",
    "Category": "Creative",
    "Price": 68990,
    "CPU_Model": "i5-13420H",
    "CPU_Gen_Series": "13",
    "GPU_Type": "RTX 3050 (6GB)",
    "TGP_W": 75,
    "Screen_Specs": "15.6\" FHD 60Hz",
    "User_Category": "Creative",
    "Series": "13th Gen (Raptor Lake)",
    "Launch Year": 2023,
    "Naming Example": "Starts with 13xxx",
    "Key Changes & Scam Detector Rule": "Excellent efficiency and performance. Highly Recommended.",
    "Recommendation": "Highly Recommended",
    "Rating": 9,
    "Purchase link": "https://www.amazon.in/s?k=HP-VICTUS-i5-13420H&i=computers"
  },
  {
    "Model_ID": "ASUS-TUF-i7-H-RTX4050",
    "Category": "Creative",
    "Price": 85000,
    "CPU_Model": "i7-13700H",
    "CPU_Gen_Series": "13",
    "GPU_Type": "RTX 4050 (6GB)",
    "TGP_W": 85,
    "Screen_Specs": "15.6\" FHD IPS 144Hz",
    "User_Category": "Creative",
    "Series": "13th Gen (Raptor Lake)",
    "Launch Year": 2023,
    "Naming Example": "Starts with 13xxx",
    "Key Changes & Scam Detector Rule": "Excellent efficiency and performance. Highly Recommended.",
    "Recommendation": "Highly Recommended",
    "Rating": 9,
    "Purchase link": "https://www.amazon.in/s?k=ASUS-TUF-i7-H-RTX4050&i=computers"
  },
  {
    "Model_ID": "LENOVO-LEGION-i7-H",
    "Category": "Creative",
    "Price": 89000,
    "CPU_Model": "i7-13700H",
    "CPU_Gen_Series": "13",
    "GPU_Type": "RTX 4060 (8GB)",
    "TGP_W": 100,
    "Screen_Specs": "16\" QHD IPS 165Hz",
    "User_Category": "Creative",
    "Series": "13th Gen (Raptor Lake)",
    "Launch Year": 2023,
    "Naming Example": "Starts with 13xxx",
    "Key Changes & Scam Detector Rule": "Excellent efficiency and performance. Highly Recommended.",
    "Recommendation": "Highly Recommended",
    "Rating": 9,
    "Purchase link": "https://www.amazon.in/s?k=LENOVO-LEGION-i7-H&i=computers"
  },
  {
    "Model_ID": "MSI-MODERN-i7-1360P",
    "Category": "Creative",
    "Price": 92000,
    "CPU_Model": "i7-1360P",
    "CPU_Gen_Series": "13",
    "GPU_Type": "Iris Xe",
    "TGP_W": 28,
    "Screen_Specs": "14\" FHD IPS 100%sRGB",
    "User_Category": "Creative",
    "Series": "12th Gen (Alder Lake)",
    "Launch Year": 2022,
    "Naming Example": "Starts with 12xxx",
    "Key Changes & Scam Detector Rule": "Introduced P-Core/E-Core Hybrid. Minimum Acceptable.",
    "Recommendation": "Acceptable",
    "Rating": 8,
    "Purchase link": "https://www.amazon.in/s?k=MSI-MODERN-i7-1360P&i=computers"
  },
  {
    "Model_ID": "ACER-ALG-13620H-RTX3050",
    "Category": "Performance",
    "Price": 73013,
    "CPU_Model": "i7-13620H",
    "CPU_Gen_Series": "13",
    "GPU_Type": "RTX 3050 (6GB)",
    "TGP_W": 75,
    "Screen_Specs": "15.6\" FHD IPS 144Hz",
    "User_Category": "Performance",
    "Series": "13th Gen (Raptor Lake)",
    "Launch Year": 2023,
    "Naming Example": "Starts with 13xxx",
    "Key Changes & Scam Detector Rule": "Excellent efficiency and performance. Highly Recommended.",
    "Recommendation": "Highly Recommended",
    "Rating": 9,
    "Purchase link": "https://www.amazon.in/s?k=ACER-ALG-13620H-RTX3050&i=computers"
  },
  {
    "Model_ID": "LENOVO-LOQ-13700HX-RTX5050",
    "Category": "Performance",
    "Price": 112002,
    "CPU_Model": "i7-13700HX",
    "CPU_Gen_Series": "13",
    "GPU_Type": "RTX 5050 (8GB)",
    "TGP_W": 120,
    "Screen_Specs": "15.6\" FHD IPS 144Hz",
    "User_Category": "Performance",
    "Series": "13th Gen (Raptor Lake)",
    "Launch Year": 2023,
    "Naming Example": "Starts with 13xxx",
    "Key Changes & Scam Detector Rule": "Excellent efficiency and performance. Highly Recommended.",
    "Recommendation": "Highly Recommended",
    "Rating": 9,
    "Purchase link": "https://www.amazon.in/s?k=LENOVO-LOQ-13700HX-RTX5050&i=computers"
  },
  {
    "Model_ID": "HP-OMNIBOOK-ULTRA7-255H",
    "Category": "Performance",
    "Price": 109990,
    "CPU_Model": "Core Ultra 7 255H",
    "CPU_Gen_Series": "14",
    "GPU_Type": "Intel Arc",
    "TGP_W": 37,
    "Screen_Specs": "14\" OLED 3K 120Hz",
    "User_Category": "Performance",
    "Series": "Core Ultra (Meteor Lake)",
    "Launch Year": 2024,
    "Naming Example": "Starts with Core Ultra",
    "Key Changes & Scam Detector Rule": "Next-gen with improved AI and efficiency. Excellent.",
    "Recommendation": "Highly Recommended",
    "Rating": 9.5,
    "Purchase link": "https://www.amazon.in/s?k=HP-OMNIBOOK-ULTRA7-255H&i=computers"
  },
  {
    "Model_ID": "ASUS-ROG-ZEPHYRUS-i9-13900HX",
    "Category": "Performance",
    "Price": 150000,
    "CPU_Model": "i9-13900HX",
    "CPU_Gen_Series": "13",
    "GPU_Type": "RTX 4070 (8GB)",
    "TGP_W": 140,
    "Screen_Specs": "16\" QHD IPS 240Hz",
    "User_Category": "Performance",
    "Series": "13th Gen (Raptor Lake)",
    "Launch Year": 2023,
    "Naming Example": "Starts with 13xxx",
    "Key Changes & Scam Detector Rule": "Excellent efficiency and performance. Highly Recommended.",
    "Recommendation": "Highly Recommended",
    "Rating": 9,
    "Purchase link": "https://www.amazon.in/s?k=ASUS-ROG-ZEPHYRUS-i9-13900HX&i=computers"
  },
  {
    "Model_ID": "LENOVO-LEGION-RYZEN9-9900HX",
    "Category": "Performance",
    "Price": 145000,
    "CPU_Model": "Ryzen 9 9900HX",
    "CPU_Gen_Series": "9000",
    "GPU_Type": "RTX 4070 (8GB)",
    "TGP_W": 140,
    "Screen_Specs": "16\" QHD IPS 240Hz",
    "User_Category": "Performance",
    "Series": "Ryzen 9000 Series (Zen 5)",
    "Launch Year": 2024,
    "Naming Example": "Starts with 9xxx",
    "Key Changes & Scam Detector Rule": "Next-gen Zen 5 with excellent performance and efficiency.",
    "Recommendation": "Highly Recommended",
    "Rating": 9.5,
    "Purchase link": "https://www.amazon.in/s?k=LENOVO-LEGION-RYZEN9-9900HX&i=computers"
  },
  {
    "Model_ID": "HP-15-i3-1315U-RF",
    "Category": "Productive",
    "Price": 39890,
    "CPU_Model": "i3-1315U",
    "CPU_Gen_Series": "13",
    "GPU_Type": "Intel Iris Xe",
    "TGP_W": 28,
    "Screen_Specs": "15.6\" FHD IPS",
    "User_Category": "Productive",
    "Series": "13th Gen (Raptor Lake)",
    "Launch Year": 2023,
    "Naming Example": "Starts with 13xxx",
    "Key Changes & Scam Detector Rule": "🔴 RED FLAG: i3 is budget tier. Entry-level performance. Poor value.",
    "Recommendation": "NOT Recommended",
    "Rating": 4,
    "Purchase link": "https://www.amazon.in/s?k=HP-15-i3-1315U-RF&i=computers"
  },
  {
    "Model_ID": "Lenovo-IdeaPad-i3-1315U-RF",
    "Category": "Productive",
    "Price": 38490,
    "CPU_Model": "i3-1315U",
    "CPU_Gen_Series": "13",
    "GPU_Type": "Intel Iris Xe",
    "TGP_W": 28,
    "Screen_Specs": "15.6\" FHD",
    "User_Category": "Productive",
    "Series": "13th Gen (Raptor Lake)",
    "Launch Year": 2023,
    "Naming Example": "Starts with 13xxx",
    "Key Changes & Scam Detector Rule": "🔴 RED FLAG: i3 is budget tier. Entry-level performance. Poor value.",
    "Recommendation": "NOT Recommended",
    "Rating": 4,
    "Purchase link": "https://www.amazon.in/s?k=Lenovo-IdeaPad-i3-1315U-RF&i=computers"
  },
  {
    "Model_ID": "HP-15-i3-1215U-RF-v1",
    "Category": "Productive",
    "Price": 32990,
    "CPU_Model": "i3-1215U",
    "CPU_Gen_Series": "12",
    "GPU_Type": "Intel Iris Xe",
    "TGP_W": 28,
    "Screen_Specs": "15.6\" FHD IPS",
    "User_Category": "Productive",
    "Series": "12th Gen (Alder Lake)",
    "Launch Year": 2022,
    "Naming Example": "Starts with 12xxx",
    "Key Changes & Scam Detector Rule": "🔴 RED FLAG: i3 is budget tier. 12th Gen is minimum acceptable but overpriced. Scam.",
    "Recommendation": "NOT Recommended",
    "Rating": 3,
    "Purchase link": "https://www.amazon.in/s?k=HP-15-i3-1215U-RF-v1&i=computers"
  },
  {
    "Model_ID": "HP-15-i3-1315U-RF-v2",
    "Category": "Productive",
    "Price": 37990,
    "CPU_Model": "i3-1315U",
    "CPU_Gen_Series": "13",
    "GPU_Type": "Intel Iris Xe",
    "TGP_W": 28,
    "Screen_Specs": "15.6\" FHD",
    "User_Category": "Productive",
    "Series": "13th Gen (Raptor Lake)",
    "Launch Year": 2023,
    "Naming Example": "Starts with 13xxx",
    "Key Changes & Scam Detector Rule": "🔴 RED FLAG: i3 is budget tier. Entry-level performance. Poor value.",
    "Recommendation": "NOT Recommended",
    "Rating": 4,
    "Purchase link": "https://www.amazon.in/s?k=HP-15-i3-1315U-RF-v2&i=computers"
  },
  {
    "Model_ID": "HP-15-i3-1215U-RF-v2",
    "Category": "Productive",
    "Price": 34990,
    "CPU_Model": "i3-1215U",
    "CPU_Gen_Series": "12",
    "GPU_Type": "Intel Iris Xe",
    "TGP_W": 28,
    "Screen_Specs": "15.6\" FHD IPS",
    "User_Category": "Productive",
    "Series": "12th Gen (Alder Lake)",
    "Launch Year": 2022,
    "Naming Example": "Starts with 12xxx",
    "Key Changes & Scam Detector Rule": "🔴 RED FLAG: i3 is budget tier. 12th Gen is minimum acceptable but overpriced. Scam.",
    "Recommendation": "NOT Recommended",
    "Rating": 3,
    "Purchase link": "https://www.amazon.in/s?k=HP-15-i3-1215U-RF-v2&i=computers"
  }
];
